
# Use postgres/example user/password credentials
version: '3.1'

services:
  db1:
    image: postgres
    volumes:
      - type: bind
        source: ./postgres/data
        target: /docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dpsa
    ports:
      - 9901:5432

  db2:
    image: postgres
    volumes:
      - type: bind
        source: ./postgres/data
        target: /docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dpsa
    ports:
      - 9902:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  #################################################################
  # aggregator server 1 (leader)
  aggregator1:
    image: mxmurw/janus_server_aggregator:latest
    volumes:
      - type: bind
        source: ./janus_server/data1
        target: /data
    ports:
      - 9991:9991

  dpsa4fl-janus-tasks1:
    image: mxmurw/janus_server_dpsa4fl-janus-tasks:latest
    volumes:
      - type: bind
        source: ./janus_server/data1
        target: /data
    ports:
      - 9981:9991

  #################################################################
  # aggregator server 2
  aggregator2:
    image: mxmurw/janus_server_aggregator:latest
    volumes:
      - type: bind
        source: ./janus_server/data2
        target: /data
    ports:
      - 9992:9992

  dpsa4fl-janus-tasks2:
    image: mxmurw/janus_server_dpsa4fl-janus-tasks:latest
    volumes:
      - type: bind
        source: ./janus_server/data2
        target: /data
    ports:
      - 9982:9992



