listen_address: 0.0.0.0:9992
max_upload_batch_size: 50
max_upload_batch_write_delay_ms: 500
database:
  url: postgres://admin:password@db2:5432/dpsa
leader_endpoint: http://aggregator1:9991
helper_endpoint: http://aggregator2:9992
external_leader: http://127.0.0.1:9991
external_helper: http://127.0.0.1:9992

